### PR TITLE
Add support for resolving "$ref" in the CLI

### PR DESCRIPTION
**Pull request by tangledbytes**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**Description**

This PR adds support for resolving $ref in the schemas. This is **not** a breaking change.

The CLI introduces a new flag `--resolve`, it expects a json path, if given it will assume that path to be the root of the openAPI spec and will attempt to resolve the references. The following must be noted:
1. If the flag is not given, the CLI will continue behaving the way it used to
2. If the flag is given but the json path evaluates to more than or less than one root then the request is ignore.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by tangledbytes** [comment]
Why do we have golangci lint and UI build workflows here? :thinking:

**Comment by leecalcote** [comment]
> Why do we have golangci lint and UI build workflows here? 🤔

Those are hold-overs from the layer5-repo-template. Let's give them the boot.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Make a release after merge?

Use the build process in PR #3?

**Comment by tangledbytes** [comment]
> Make a release after merge?
> 
> Use the build process in PR #3?

We are not using the make recipes. I think we can use them :thinking:

**Comment by leecalcote** [comment]
I hear you saying that you'd think it's a good idea not to repeat ourselves, not to repeat ourselves, to repeat ourselves, repeat ourselves.

**Pull request merged**
