### PR TITLE
[CI] Add build and release workflow

### LINKED ISSUE #2: [CI] Build and Release workflow to produce binary artifacts
#### Current Behavior
A build and release workflow is missing for this repo.

#### Desired Behavior
Meshery Adapters that need to use this utility will ideally reference https://github.com/layer5io/kubeopenapi-jsonschema/releases/latest for a copy of the latest binaries for this utility.

#### Implementation
1. Create a workflow that triggers on a Release event.
1. Build the utilities binaries (minimally for Linux arch, with Win and Mac being nice-to-have).
1. Capture and persist the binaries in as Release artifacts.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by iamsdas**
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>

**Description**
Workflow to build and release binary artifacts on release

This PR fixes #2 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This doesn't publish the build artifacts, does it?

**Comment by tangledbytes** [comment]
@iamsdas instead of explicitly running nexe for every platform, can't we just run `make` ? There are make recipes for the platforms. Is there any issue with this approach?

**Comment by iamsdas** [comment]
> This doesn't publish the build artifacts, does it?

What this does is that, it takes the latest release and adds the artifacts to it. So technically it does publish it (this is what it is supposed to do right?)

**Comment by iamsdas** [comment]
> @iamsdas instead of explicitly running nexe for every platform, can't we just run `make` ? There are make recipes for the platforms. Is there any issue with this approach?

We can definitely do that too, I did it like this because I originally tested the workflow with only one platform (Linux), then later on I added the others manually forgetting about the make file. I'll change it to use the makefile

**Review by DelusionalOptimist — COMMENTED** [review]
Awesome work @iamsdas :v:
A binary with `alpine` as compilation target is also needed now to work with Meshery server. It would need to be compiled with node `v12.9.1`. Let's try to get this workflow generate it too : )

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
