### PR TITLE
docs: Remove background from readme image

### LINKED ISSUE #7: [Docs] Replace image in README file
**Current  #State:**
See the white background between the man and woman in the image below that needs to be updated to a better version in the README file.

meshery image issue

**Desired State:**
This is the desired image.
meshery image

Replace with the image below.

layer5-community-sign

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by ArturBa**
**Description**

This PR fixes #7 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@ArturBa are you sure this replaces the image in the readme? I don't see the previous image deleted or a change in path name in the readme. A screenshot would be great.

**Comment by ArturBa** [comment]
@warunicorn19 
Hi, I've replaced the old image (with the background issue) using the new one.
You might check it [there](https://github.com/ArturBa/kubeopenapi-jsonschema/tree/master#join-the-service-mesh-community). Remember to clean browsers cache :wink: 

Screen:
Screenshot_20211004_184238

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you @ArturBa 😄

**Comment by ArturBa** [comment]
Hi. 
The tag you have added doesn't seem to work on hacktoberfest page. 
Can you please check it? 
This is a information from hacktoberfest page
Screenshot_20211006-065433_Chrome

**Pull request merged**
